In [11]:
import pandas as pd
import numpy as np

In [12]:
df = pd.read_csv('EDA-ed_Laptop.csv')
df.tail()

,TypeName,Inches,ScreenResolution,Cpu,Ram,OpSys,Weight,TouchScreen,HDD,SSD,SSHD,FStorage,Price
1297,2 in 1 Convertible,14.0,1920x1080,Intel i7,4,Windows 10,1.80,Yes,0,128,0,0,638.0
1298,2 in 1 Convertible,13.3,3200x1800,Intel i7,16,Windows 10,1.30,Yes,0,512,0,0,1499.0
1299,Notebook,14.0,1366x768,Intel Celeron,2,Windows 10,1.50,No,0,0,0,64,229.0
1300,Notebook,15.6,1366x768,Intel i7,6,Windows 10,2.19,No,1000,0,0,0,764.0
1301,Notebook,15.6,1366x768,Intel Celeron,4,Windows 10,2.20,No,500,0,0,0,369.0

In [13]:
df.dtypes

TypeName             object
Inches              float64
ScreenResolution     object
Cpu                  object
Ram                   int64
OpSys                object
Weight              float64
TouchScreen          object
HDD                   int64
SSD                   int64
SSHD                  int64
FStorage              int64
Price               float64
dtype: object

In [14]:
#Prints all columns that are of type object

for i in df.columns:
     if df[i].dtype=='object':
             print("%-10s\n%-200s\n%-10d\n"%(i,df[i].unique(),df[i].nunique()))

TypeName
['Ultrabook' 'Notebook' 'Netbook' 'Gaming' '2 in 1 Convertible'
 'Workstation']
6

ScreenResolution
['2560x1600' '1440x900' '1920x1080' '2880x1800' '1366x768' '2304x1440'
 '3200x1800' '1920x1200' '2256x1504' '3840x2160' '2160x1440' '2560x1440'
 '1600x900' '2400x1600']
14

Cpu
['Intel i5' 'Intel i7' 'AMD A9' 'Intel i3' 'Intel M ' 'Intel Atom' 'AMD E'
 'AMD A6' 'Intel Celeron' 'AMD Ryzen' 'Intel Pentium' 'AMD FX'
 'Intel Xeon' 'AMD A10' 'AMD A8' 'AMD A12' 'AMD A4' 'Samsung']
18

OpSys
['macOS' 'No OS' 'Windows 10' 'Mac OS X' 'Linux' 'Android' 'Windows 10 S'
 'Chrome OS' 'Windows 7']
9

TouchScreen
['No' 'Yes']
2

In [15]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()

print(df['TouchScreen'].unique())
print(le.fit_transform(df['TouchScreen'].unique())) # to check what encoded values would be

['No' 'Yes']
[0 1]

In [16]:
df['TouchScreen']=le.fit_transform(df['TouchScreen'])
df.tail()

,TypeName,Inches,ScreenResolution,Cpu,Ram,OpSys,Weight,TouchScreen,HDD,SSD,SSHD,FStorage,Price
1297,2 in 1 Convertible,14.0,1920x1080,Intel i7,4,Windows 10,1.80,1,0,128,0,0,638.0
1298,2 in 1 Convertible,13.3,3200x1800,Intel i7,16,Windows 10,1.30,1,0,512,0,0,1499.0
1299,Notebook,14.0,1366x768,Intel Celeron,2,Windows 10,1.50,0,0,0,0,64,229.0
1300,Notebook,15.6,1366x768,Intel i7,6,Windows 10,2.19,0,1000,0,0,0,764.0
1301,Notebook,15.6,1366x768,Intel Celeron,4,Windows 10,2.20,0,500,0,0,0,369.0

One Hot encoding will be used to preprocess nominal columns with low cardinality (TypeName and OpSYs will be one hot encoded)

In [17]:
pd.DataFrame(df['TypeName'])

                TypeName
0              Ultrabook
1              Ultrabook
2               Notebook
3              Ultrabook
4              Ultrabook
...                  ...
1297  2 in 1 Convertible
1298  2 in 1 Convertible
1299            Notebook
1300            Notebook
1301            Notebook

[1302 rows x 1 columns]

In [18]:
dummTypeName = pd.get_dummies(df['TypeName'])
dummTypeName

      2 in 1 Convertible  Gaming  Netbook  Notebook  Ultrabook  Workstation
0                      0       0        0         0          1            0
1                      0       0        0         0          1            0
2                      0       0        0         1          0            0
3                      0       0        0         0          1            0
4                      0       0        0         0          1            0
...                  ...     ...      ...       ...        ...          ...
1297                   1       0        0         0          0            0
1298                   1       0        0         0          0            0
1299                   0       0        0         1          0            0
1300                   0       0        0         1          0            0
1301                   0       0        0         1          0            0

[1302 rows x 6 columns]

In [19]:
dummOpSys = pd.get_dummies(df['OpSys'])
dummOpSys

,Android,Chrome OS,Linux,Mac OS X,No OS,Windows 10,Windows 10 S,Windows 7,macOS
0,0,0,0,0,0,0,0,0,1
1,0,0,0,0,0,0,0,0,1
2,0,0,0,0,1,0,0,0,0
3,0,0,0,0,0,0,0,0,1
4,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...
1297,0,0,0,0,0,1,0,0,0
1298,0,0,0,0,0,1,0,0,0
1299,0,0,0,0,0,1,0,0,0
1300,0,0,0,0,0,1,0,0,0
1301,0,0,0,0,0,1,0,0,0

In [20]:
df.head()

,TypeName,Inches,ScreenResolution,Cpu,Ram,OpSys,Weight,TouchScreen,HDD,SSD,SSHD,FStorage,Price
0,Ultrabook,13.3,2560x1600,Intel i5,8,macOS,1.37,0,0,128,0,0,1339.69
1,Ultrabook,13.3,1440x900,Intel i5,8,macOS,1.34,0,0,0,0,128,898.94
2,Notebook,15.6,1920x1080,Intel i5,8,No OS,1.86,0,0,256,0,0,575.00
3,Ultrabook,15.4,2880x1800,Intel i7,16,macOS,1.83,0,0,512,0,0,2537.45
4,Ultrabook,13.3,2560x1600,Intel i5,8,macOS,1.37,0,0,256,0,0,1803.60

In [21]:
df.drop(columns=['TypeName','OpSys'],inplace=True)
OH_df = pd.concat([df,dummTypeName,dummOpSys], axis=1)

pd.set_option('display.max_columns', None)
OH_df.head()

,Inches,ScreenResolution,Cpu,Ram,Weight,TouchScreen,HDD,SSD,SSHD,FStorage,Price,2 in 1 Convertible,Gaming,Netbook,Notebook,Ultrabook,Workstation,Android,Chrome OS,Linux,Mac OS X,No OS,Windows 10,Windows 10 S,Windows 7,macOS
0,13.3,2560x1600,Intel i5,8,1.37,0,0,128,0,0,1339.69,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1
1,13.3,1440x900,Intel i5,8,1.34,0,0,0,0,128,898.94,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1
2,15.6,1920x1080,Intel i5,8,1.86,0,0,256,0,0,575.00,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0
3,15.4,2880x1800,Intel i7,16,1.83,0,0,512,0,0,2537.45,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1
4,13.3,2560x1600,Intel i5,8,1.37,0,0,256,0,0,1803.60,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1

In [22]:
OH_df['LaptopPrice']=OH_df['Price']
OH_df.drop(columns=['Price'],inplace = True)
OH_df

,Inches,ScreenResolution,Cpu,Ram,Weight,TouchScreen,HDD,SSD,SSHD,FStorage,2 in 1 Convertible,Gaming,Netbook,Notebook,Ultrabook,Workstation,Android,Chrome OS,Linux,Mac OS X,No OS,Windows 10,Windows 10 S,Windows 7,macOS,LaptopPrice
0,13.3,2560x1600,Intel i5,8,1.37,0,0,128,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1339.69
1,13.3,1440x900,Intel i5,8,1.34,0,0,0,0,128,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,898.94
2,15.6,1920x1080,Intel i5,8,1.86,0,0,256,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,575.00
3,15.4,2880x1800,Intel i7,16,1.83,0,0,512,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,2537.45
4,13.3,2560x1600,Intel i5,8,1.37,0,0,256,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1803.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1297,14.0,1920x1080,Intel i7,4,1.80,1,0,128,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,638.00
1298,13.3,3200x1800,Intel i7,16,1.30,1,0,512,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1499.00
1299,14.0,1366x768,Intel Celeron,2,1.50,0,0,0,0,64,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,229.00
1300,15.6,1366x768,Intel i7,6,2.19,0,1000,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,764.00
1301,15.6,1366x768,Intel Celeron,4,2.20,0,500,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,369.00

Label encoding would be used to encode ScreenResolution column as order matters (low res to high res)

In [23]:
Screen_Res_dict={'1366x768' : 1, '1440x900' : 2 , '1600x900': 3, '1920x1080': 4, '1920x1200': 5, '2160x1440': 6, 
                 '2304x1440': 7, '2256x1504': 8, '2560x1440': 9, '2400x1600':10, '2560x1600':11, '2880x1800':12, 
                  '3200x1800': 13, '3840x2160':14}

OH_df['ScreenResolution'] = OH_df.ScreenResolution.map(Screen_Res_dict)

OH_df

,Inches,ScreenResolution,Cpu,Ram,Weight,TouchScreen,HDD,SSD,SSHD,FStorage,2 in 1 Convertible,Gaming,Netbook,Notebook,Ultrabook,Workstation,Android,Chrome OS,Linux,Mac OS X,No OS,Windows 10,Windows 10 S,Windows 7,macOS,LaptopPrice
0,13.3,11,Intel i5,8,1.37,0,0,128,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1339.69
1,13.3,2,Intel i5,8,1.34,0,0,0,0,128,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,898.94
2,15.6,4,Intel i5,8,1.86,0,0,256,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,575.00
3,15.4,12,Intel i7,16,1.83,0,0,512,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,2537.45
4,13.3,11,Intel i5,8,1.37,0,0,256,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1803.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1297,14.0,4,Intel i7,4,1.80,1,0,128,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,638.00
1298,13.3,13,Intel i7,16,1.30,1,0,512,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1499.00
1299,14.0,1,Intel Celeron,2,1.50,0,0,0,0,64,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,229.00
1300,15.6,1,Intel i7,6,2.19,0,1000,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,764.00
1301,15.6,1,Intel Celeron,4,2.20,0,500,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,369.00

Label encoding applies to CPU as well

In [24]:
Cpu_list = list(OH_df['Cpu'].unique())

Cpu_le = list(le.fit_transform(OH_df['Cpu'].unique()))

for i in range(0, len(Cpu_list)):
    print("%-20s%d"%(Cpu_list[i], Cpu_le[i]))

Intel i5            15
Intel i7            16
AMD A9              5
Intel i3            14
Intel M             11
Intel Atom          9
AMD E               6
AMD A6              3
Intel Celeron       10
AMD Ryzen           8
Intel Pentium       12
AMD FX              7
Intel Xeon          13
AMD A10             0
AMD A8              4
AMD A12             1
AMD A4              2
Samsung             17

In [25]:
OH_df['Cpu'] = le.fit_transform(OH_df['Cpu'])
OH_df

,Inches,ScreenResolution,Cpu,Ram,Weight,TouchScreen,HDD,SSD,SSHD,FStorage,2 in 1 Convertible,Gaming,Netbook,Notebook,Ultrabook,Workstation,Android,Chrome OS,Linux,Mac OS X,No OS,Windows 10,Windows 10 S,Windows 7,macOS,LaptopPrice
0,13.3,11,15,8,1.37,0,0,128,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1339.69
1,13.3,2,15,8,1.34,0,0,0,0,128,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,898.94
2,15.6,4,15,8,1.86,0,0,256,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,575.00
3,15.4,12,16,16,1.83,0,0,512,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,2537.45
4,13.3,11,15,8,1.37,0,0,256,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1803.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1297,14.0,4,16,4,1.80,1,0,128,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,638.00
1298,13.3,13,16,16,1.30,1,0,512,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1499.00
1299,14.0,1,10,2,1.50,0,0,0,0,64,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,229.00
1300,15.6,1,16,6,2.19,0,1000,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,764.00
1301,15.6,1,10,4,2.20,0,500,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,369.00

# Saving processed data to csv

In [26]:
OH_df.to_csv('final_df.csv',index=False)